controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
  
    position_velocity_effort_gain_controller:
      type: position_velocity_effort_gain_controller/PosVelTorGainsController

forward_position_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
    interface_name: position

position_velocity_effort_gain_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
    origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    interface_name: gain_kp
