controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    default_kp: 1000.0
    default_kd: 10.0

    pveg_controller:
      type: position_velocity_effort_gain_controller/PosVelTorGainsController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pveg_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
    origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    interface_names: [position,velocity,effort,gain_kp,gain_kd]
