controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    default_kp: 1000.0
    default_kd: 10.0

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    pveg_controller:
      type: position_velocity_effort_gain_controller/PosVelTorGainsController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_HFE
      - FR_HFE
      - FL_KFE
      - FR_KFE
    origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    interface_name: position

pveg_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FR_HAA
      - FL_HFE
      - FR_HFE
      - FL_KFE
      - FR_KFE
    origin: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    interface_names: [position,velocity,effort,gain_kp,gain_kd]
